baseurl = "https://2023.gophercon.sg/"
languageCode = "en-SG"
title = "GopherCon Singapore 2023"
theme = "gopherconsg-2017"

[params]
name = "GopherCon Singapore"
description = "GopherCon Singapore is a Go programming language (Golang) conference in Southeast Asia."
ogimage = "gopherconsg2023.png"

# Navigation
[params.navigation.brand]
png = "gopherconsg2023-long.png"
